POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Product 3",
  "price": 10.00
}
###
GET http://localhost:3000/products
###
GET http://localhost:3000/products/9
###
PATCH  http://localhost:3000/products/8
Content-Type: application/json

{
  "price": 12.90
}
###
DELETE http://localhost:3000/products/9